#!/bin/bash
#
# mart-dhis2-sync        start/stop/status script
#
# chkconfig: - 64 36
# description: mart-dhis2-sync - Integration of MART and DHIS Sync
# processname: mart-dhis2-sync
# pidfile: /var/run/mart-dhis2-sync.pid
### BEGIN INIT INFO
# Provides: mart-dhis2-sync
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop mart-dhis2-sync system,
# Description: mart-dhis2-sync system
### END INIT INFO

export MART_DHIS_USER=bahmni
export MART_DHIS_RUN=/opt/mart-dhis2-sync/bin/start.sh
export MART_DHIS_DEBUG=/opt/mart-dhis2-sync/bin/debug.sh
export CUR_USER=`/usr/bin/whoami`


. /etc/mart-dhis2-sync/mart-dhis.conf

create_dirs() {
    if [[ ! -e /var/log/mart-dhis2-sync ]]; then
        ln -s /opt/mart-dhis2-sync/log /var/log/mart-dhis2-sync
    fi
}

mart_dhis_pid() {
        echo `ps -fe | grep 'mart-dhis2-sync.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(mart_dhis_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService mart-dhis2-sync is already running (pid: $pid)\e[00m"
    else
        # Start mart-dhis2-sync
        create_dirs
        echo -e "\e[00;32mStarting mart-dhis2-sync\e[00m"
        if [ `user_exists $MART_DHIS_USER` = "1" ]  && [ "$CUR_USER" != "$MART_DHIS_USER" ] ;
        then
                su -s /bin/bash $MART_DHIS_USER $MART_DHIS_RUN
        else
                sh $MART_DHIS_RUN
        fi
  fi
  exit 0
}

debug(){
    pid=$(mart_dhis_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService mart-dhis2-sync is already running (pid: $pid)\e[00m"
    else
        # Start mart-dhis2-sync
        create_dirs
        echo -e "\e[00;32mStarting mart-dhis2-sync\e[00m"
        if [ `user_exists $MART_DHIS_USER` = "1" ]  && [ "$CUR_USER" != "$MART_DHIS_USER" ] ;
        then
                su -s /bin/bash $MART_DHIS_USER $MART_DHIS_DEBUG
        else
                sh $MART_DHIS_DEBUG
        fi
  fi
  exit 0
}

status(){
          pid=$(mart_dhis_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService mart-dhis2-sync is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService mart-dhis2-sync is not running\e[00m"
          exit 3
          fi
}

stop() {
	echo -e "\e[00;31mTerminating mart-dhis2-sync\e[00m"
	kill -9 $(mart_dhis_pid)
	rm -rf /var/run/mart-dhis2-sync/mart-dhis2-sync.pid
	return
}

user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
    debug)
	  debug
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0